// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7-2DnPlOLOXwQKOdYIRp8s4AOPWnJI9Q',
    appId: '1:578590871850:web:eda507144a0e74586b8e53',
    messagingSenderId: '578590871850',
    projectId: 'attendenceapp-12046',
    authDomain: 'attendenceapp-12046.firebaseapp.com',
    storageBucket: 'attendenceapp-12046.firebasestorage.app',
    measurementId: 'G-VWXJBLDVQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzQCgmX_lua8OprlbJqUAK3v6LivcWLE',
    appId: '1:578590871850:android:fa311cffe95e2db26b8e53',
    messagingSenderId: '578590871850',
    projectId: 'attendenceapp-12046',
    storageBucket: 'attendenceapp-12046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8tJVYWB0JUIc2g_ZQvUmlV3uscN3DJEc',
    appId: '1:578590871850:ios:3412f3a43a9da88a6b8e53',
    messagingSenderId: '578590871850',
    projectId: 'attendenceapp-12046',
    storageBucket: 'attendenceapp-12046.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8tJVYWB0JUIc2g_ZQvUmlV3uscN3DJEc',
    appId: '1:578590871850:ios:3412f3a43a9da88a6b8e53',
    messagingSenderId: '578590871850',
    projectId: 'attendenceapp-12046',
    storageBucket: 'attendenceapp-12046.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7-2DnPlOLOXwQKOdYIRp8s4AOPWnJI9Q',
    appId: '1:578590871850:web:31fdcd323db477c46b8e53',
    messagingSenderId: '578590871850',
    projectId: 'attendenceapp-12046',
    authDomain: 'attendenceapp-12046.firebaseapp.com',
    storageBucket: 'attendenceapp-12046.firebasestorage.app',
    measurementId: 'G-QYKNP1NH6R',
  );
}
