// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNQrdif89CTEptedCsP1ZBOXpHJXCByM',
    appId: '1:513666985062:web:97363f990811edaf1691a7',
    messagingSenderId: '513666985062',
    projectId: 'attendance-app-e25b6',
    authDomain: 'attendance-app-e25b6.firebaseapp.com',
    storageBucket: 'attendance-app-e25b6.firebasestorage.app',
    measurementId: 'G-WLMBR70XD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeUiMgIX8-Xg-uQkz8TjskkiH3bEw1NWg',
    appId: '1:513666985062:android:75095c4d378034b91691a7',
    messagingSenderId: '513666985062',
    projectId: 'attendance-app-e25b6',
    storageBucket: 'attendance-app-e25b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZXY7swV-Ria7pyQjVxw7__yci294G9U',
    appId: '1:513666985062:ios:4ccf28512afb8c8f1691a7',
    messagingSenderId: '513666985062',
    projectId: 'attendance-app-e25b6',
    storageBucket: 'attendance-app-e25b6.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPZXY7swV-Ria7pyQjVxw7__yci294G9U',
    appId: '1:513666985062:ios:4ccf28512afb8c8f1691a7',
    messagingSenderId: '513666985062',
    projectId: 'attendance-app-e25b6',
    storageBucket: 'attendance-app-e25b6.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRNQrdif89CTEptedCsP1ZBOXpHJXCByM',
    appId: '1:513666985062:web:65e1e01b009198541691a7',
    messagingSenderId: '513666985062',
    projectId: 'attendance-app-e25b6',
    authDomain: 'attendance-app-e25b6.firebaseapp.com',
    storageBucket: 'attendance-app-e25b6.firebasestorage.app',
    measurementId: 'G-7MCT8QKBHM',
  );
}
